### ISSUE TITLE
Any way to export two tables stacked on top of each other?

### ISSUE THREAD

**Issue by HarshDoug** [zachwick/TableCSVExport#13]
i tried to do so, both with two tables with the same class name, and also passing in two ids. Both ways, the resulted formatting is worng.

**Comment by rubo77** [comment]
Csv doesn't support Microsoft excel table layers

**Comment by HarshDoug** [comment]
So there's no way to export two tables to the same csv file?

**Comment by rubo77** [comment]
try create an openoffice document with two table layers and store it as CSV.

not supported by the text-only format CSV
